services:
  frontend-nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm run build && npm run dev"

volumes:
  frontend_node_modules:
