services:
  frontend-nextjs:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=production

  backend-go:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - go-mod:/go/pkg/mod
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  frontend_node_modules:
  postgres_data:
  go-mod:
