services:
  frontend-nextjs:
    build:
      context: ../../frontend
      dockerfile: ../../docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=production
    command: sh -c "npm cache clean --force && rm -rf .next/cache && npm run build && npm run dev"

volumes:
  frontend_node_modules:
